config/routes.rb
Rails.application.routes.draw do
  get 'employees/index'

  get 'employees/new'

  get 'employees/edit'

  get 'employees/create'

  resources :students
  get "/preethi" => "students#index"
  resources :employees 
  get "/kathir" => "employees#index"

end

app/models/employee.rb
class Employee < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  def index
  	
  end

  def new
  	@employee = Employee.new 
  end

  def edit
  	@employee = Employee.find(params[:id])
  end

  def create
  	o = Employee.new(params.require(:employee).permit!)
    o.save
	redirect_to "/preethi"
  end

  def update
  	o = Employee.find(params[:id])
  	o.update_attributes(params.require(:employee).permit!)
  	redirect_to preethi_path
  end

  def destroy
  	o = Employee.find(params[:id])
  	o.destroy
  	redirect_to preethi_path
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	def index
		@students = Student.all
		@employees = Employee.all
	end

	def new
		@student = Student.new
	end

	def edit
		@student = Student.find(params[:id])
	end

	def create
		o = Student.new(params.require(:student).permit!)
		o.save
		redirect_to "/preethi"
	end
	def destroy
		o= Student.find(params[:id])
	    o.destroy
	    redirect_to preethi_path
	end


    def update
		o= Student.find(params[:id])
	    o.update_attributes(params.require(:student).permit!)
	    redirect_to preethi_path
	end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/employees/_form.html.erb


<%= form_for(@employee) do |f| %>
   Name:
   <%= f.text_field :name %>
   <br/>
   Emp id:
   <%= f.text_field :emp_id %>
   <br/>
   Dept:
   <%= f.text_field :department %>
   <br/>

   <%= f.submit "Do magic" %>
<% end %>   

app/views/employees/create.html.erb
<h1>Employees#create</h1>
<p>Find me in app/views/employees/create.html.erb</p>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render "form" %>

app/views/employees/index.html.erb
<h1>Employees#index</h1>
<p>Find me in app/views/employees/index.html.erb</p>

app/views/employees/new.html.erb
<h1>Creating employee</h1>

<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/_form.html.erb


<%= form_for(@student) do |f| %>
   First Name:
   <%= f.text_field :first_name %>
   <br/>
   Last Name:
   <%= f.text_field :last_name %>
   <br/>
   Student_Id:
   <%= f.text_field :stu_id %>
   <br/>

   <%= f.submit "Do magic" %>
<% end %>   

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form" %>

app/views/students/index.html.erb

<html>
<head>
<style>

div
{
   width: 900px;
   padding: 50px;
   border: 25px solid blue;
   margin: 20px;
 }

img{
  float:top-left;
 }
 

table, td, th {
    border: 1px solid black;
}

table {
    
    padding: 15px;
    border-collapse: collapse;
    width: 100%;
}

th {
    font-style:bold; 
    background-color: #f2f2f2;
    height: 50px;
}


h1
{
  color: green;
  text-align:left;
  font-family:"Monospace";
  font-style:italic;
 }
</style> </head>

<body>
 
<img src="capp.jpg" width="105" height="116"/>
<div>
<%= link_to "New student",new_student_path %>
<br/>
<h1> Student's Database </h1>
<table border=1>
  <thead>
  	<th>first_name</th>
    <th>last_name</th>
    <th>Stu_id</th>
    <th>Edit</th>
    <th>Delete</th>
 </thead>
   
  <tbody>
	  <% @students.each do |s| %>
	    <tr>
	      <td><%= s.first_name %></td>
	      <td><%= s.last_name %></td>
	      <td><%= s.stu_id %></td>
	      <td><%= link_to "edit","/students/#{s.id}/edit" %></td>
	      <td><%= link_to "delete",s,{method: :delete} %></td>
	  </tr>
  <% end %>
  </tbody>
</table>

</br>

<%= link_to "New Staff",new_employee_path %>
<h1> Staff's Database </h1>
<table border=1>
  <thead>
  	<th>emp_name</th>
    <th>emp_id</th>
    <th>dept</th>
    <th>Edit</th>
    <th>Delete</th>
  </thead>
   
  <tbody>
	  <% @employees.each do |i| %>
	    <tr>
	      <td><%= i.name %></td>
	      <td><%= i.emp_id %></td>
	      <td><%= i.department %></td>
	      <td><%= link_to "edit","/employees/#{i.id}/edit" %></td>
	      <td><%= link_to "delete",i,{method: :delete} %></td>
	    </tr>
	  <% end %>
  </tbody>
  </table>
</div>
</body>
</html>

app/views/students/new.html.erb
<h1>Creating student</h1>

<%= render "form" %>